name: Auto Update LeetCode Count

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Lấy toàn bộ lịch sử git để tránh lỗi khi rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run count script
        run: python update_readme.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          
          # Chỉ xử lý nếu có sự thay đổi con số
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: update leetcode solved count [skip ci]"
            # Kéo code mới nhất về và chồng commit của Actions lên trên cùng để tránh xung đột
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes detected in README.md"
          fi
